services:
  app:
    container_name: agn-app
    build: .
    volumes:
      - .:/var/www/html
    networks:
      - agn-network

  nginx:
    container_name: agn-nginx
    image: nginx:latest
    volumes:
      - ./src:/var/www/html 
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "8000:80"
    depends_on:
      - app 
    networks:
      - agn-network

  postgres:
    container_name: agn-postgres
    image: postgres:16.4
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - agn-network

volumes:
  postgres:

networks:
  agn-network:
    driver: bridge
